kind: "AppHostingYaml"
apiVersion: "v1"
runConfig:
  cpu: 1
  memoryMiB: 512
  maxInstances: 10
  minInstances: 0
  concurrency: 80
env:
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyACaAHYZtenp6AGjO9LkQGNzDmXw7u2xwA"
  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: "the-excelling-learner.firebaseapp.com"
  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: "the-excelling-learner"
  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: "the-excelling-learner.firebasestorage.app"
  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "511003783773"
  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: "1:511003783773:web:4493cf0d97cf48038993b4"
  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: "G-HRY73JZMBN"
